Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-03c7d01cf4dedc891
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, instance, from, cloudformation]]