Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-03c7d01cf4dedc891
      Tags:
        - Key: "Name"
          Value: !Join ["-", [my, instance, from, cloudformation]]
      SecurityGroups:
        - !Ref VprofileSG

  VprofileSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow ssh & http from MyIP
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 112.205.150.42/32
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 112.205.150.42/32